### ISSUE TITLE
WebSocket data stops coming

### ISSUE THREAD

**Issue by IlyaBelyaev** [Bittrex/bittrex.github.io#105]
Hi, i found a problem with receiving data by WebSocket, after some time (usually 30 minutes - 4 hours), data updates for the order book stops coming, without errors. Ping-pong successfully comes.

Subscribe to a lot of markets. Messages stop coming every time for a random market.

URI: "wss: //socket.bittrex.com/signalr".
Method: "SubscribeToExchangeDeltas"
Found this problem by using library (node js) "signalr-client", then re-write connection by "ws" library. Problem still exists.

I tried to hang a lot of subscriptions on one socket. And also tried open a new WebSocket connection for each subscription. Problem still exists.

Handle message method:
```
const jsonic = require('jsonic');
const zlib = require('zlib');

handleMessage(msg){
    // (1)
    let data = jsonic(msg.utf8Data);

    if (data.hasOwnProperty('M')) {
      for (let i = 0 ; i < data.M.length; i++) {
        let dataM = data.M[i];

        if (dataM) {
          if (dataM.hasOwnProperty('A')) {
            if (dataM.A[0]) {
              let b64 = dataM.A[0];
              let raw = new Buffer.from(b64, 'base64');

              zlib.inflateRaw(raw, (err, inflated) => {
                if (!err) {
                  let json = JSON.parse(inflated.toString('utf8'));

                  this.update(json);
                }
              });
            }
          }
        }
      }
    }
  }
```

In place (1) saved the current time stamp. Updates don't come. There can't be an error in "handleMessage" method.

I suppose I don’t handle errors, the documentation doesn't say anything about this.

Node js v12.14.0

**Comment by laserlance** [comment]
Please see the heading "Socket Connections" at the following page, which explains this: https://bittrex.github.io/api/v1-1

**Comment by IlyaBelyaev** [comment]
The problem is that the moment when you need to reconnect is unclear. Let's say the eth-btc token is updated every second, and the conditional noname-btc once every few minutes. Should I constantly reconnect on noname-btc? I think we need to get a disconnect event from the server for start reconnecting.

**Comment by laserlance** [comment]
Are you sure that noname-btc has traded in the time you are expecting? In my experience, not all markets have trades every second, and trading on the Bittrex exchange is relatively low compared to other exchanges. So, it could be that what you are experiencing is that trades aren't happening.

The way to test this is to look at the REST endpoint for noname-btc and see if the market is trading. 

That said, I don't know if it still happens, but I used to miss trades on the websocket. But I had redundancy built in so I got data from both the REST endpoint and the websocket. The data went into the same database. Because the websocket has a nice value, I could tell which trades were captured via websocket and which via the REST endpoint. Admittedly, I haven't looked at this in a while so they may have fixed this.

**Comment by cyrus19909** [comment]
@IlyaBelyaev as what @laserlance not all markets have trades every second which could be an explanation of the above issue you are facing. If you keep on facing the issue over a high intensity market, i would recommend capturing the nonces and make sure that they are sequential. You can write up a logic where if a nonce was skipped, you can do a retry to the socket and resubscribe to make sure that your db is consistent with the recent updates. If that also doesnt help , sometime alternating between multiple socket connection helps as well. Let me know if the above suggestion helps and if we can do anything else to help
