### ISSUE TITLE
Don't work GET /markets/{marketSymbol}/candles/{candleInterval}/historical/{year}/{month}/{day}

### ISSUE THREAD

**Issue by Xsys04** [Bittrex/bittrex.github.io#152]
Here is a list of queries. Some work, while others do not. Can you check the consistency of the requests with the documentation?

https://global.bittrex.com/v3/markets/DGB-BTC/candles/HOUR_1/historical/2020/05
https://global.bittrex.com/v3/markets/DGB-BTC/candles/DAY_1/historical/2020/05
https://global.bittrex.com/v3/markets/DGB-BTC/candles/DAY_1/historical/2020
https://global.bittrex.com/v3/markets/DGB-BTC/candles/DAY_1/historical/2019
https://global.bittrex.com/v3/markets/DGB-BTC/candles/DAY_1/recent

**Comment by cyrus19909** [comment]
Hi @Xsys04 ,

The above issue seems to be because of the interval period you are passing the request . According to the documentation the interval parameters mean the following :

`The date range of returned candles depends on the interval as follows: (MINUTE_1: 1 day, MINUTE_5: 1 day, HOUR_1: 31 days, DAY_1: 366 days)`

Correct : https://global.bittrex.com/v3/markets/DGB-BTC/candles/HOUR_1/historical/2020/05 (for the month)
Correct : https://global.bittrex.com/v3/markets/DGB-BTC/candles/MINUTE_1/historical/2020/05/01 (specific date on a minute basis )
Correct : https://global.bittrex.com/v3/markets/DGB-BTC/candles/MINUTE_5/historical/2020/05/01 (specific date on a 5 minute basis )
Incorrect : https://global.bittrex.com/v3/markets/DGB-BTC/candles/DAY_1/historical/2020 (reason being that DAY_1 return 366 days over all , hence the year 2019 works fine .


Please let us know if this makes things a little more clear .
