### ISSUE TITLE
There was an error invoking Hub method 'c2.GetAuthContext'

### ISSUE THREAD

**Issue by UtilZone** [Bittrex/bittrex.github.io#16]
I am developing an application in Adobe AIR (ActionScript) using the AS3 library signalRF by michas.

https://libraries.io/github/jmichas/SignalRF

Connection established through "c2" hub successfully. But when I try to authenticate through the method GetAuthContext, it gives error ...

"There was an error invoking Hub method 'c2.GetAuthContext'"

The message sent to server is :
{"M":"GetAuthContext","H":"c2","S":{},"I":"0","A":[""]}

**Comment by nanvel** [comment]
The same issue in https://github.com/nanvel/aiobittrex/issues/3
```
There was an error invoking Hub method 'c2.Authenticate'
```

**Comment by ape364** [comment]
opened issues show that bittrex team don't care it :( there is no other way to inform them about this problem?

**Comment by pdotmidge** [comment]
We don't generally provide assistance to folks writing their own libraries, which we're grateful people want to do, because it'd be a support nightmare. That said, the authentication sequence works in all reference libraries, so I'd suggest taking a look at the existing [sample code](https://github.com/Bittrex/bittrex.github.io/tree/master/samples).
