### ISSUE TITLE
Feature requests and questions, REST v3

### ISSUE THREAD

**Issue by Serpens66** [Bittrex/bittrex.github.io#162]
I just implemented REST API v3 and found:

### Important

**Trading Fee**
#161

**MinTradeSize**
why does the "MinTradeSize" returned from "markets" often has such strange numbers, eg currently for BTC-EUR: 'minTradeSize': '0.00044994' Does this mean this size is changing everytime the price of BTC changes? So I'm supposed to check this endpoint every single time before placing a small order? Or how does it work?
If it is indeed changing frequently, is there a websocket channel to get notified about the changes?
Of course it would be much better to add a "minQuoteSize" value and set it to eg. 5 EUR in this case. Like all other exchanges do it.

**Place Order:**
the "useAwards" system also could be better... of course I want to use it whenever possible, but to add the logic to check if the left amount in balance is enough to cover it is very tedious, especially when you have to convert your expected tradingfee in BTC to USD to credits to know how much credits you might need. How about not letting the order fail in case not enough credits are left and instead place it like a normal order? (or make this optional to not let the order fail) 

**Get Executions (Trades)**
A private call to get all executions regardless of the order_id is missing. This is very important for calculating the real profit one made, since the closed_order prices are not acutally matched prices.
Or does the field "proceeds" contain the total really paid sum (not rounded!), even if the order was matched in several executions with different prices?

**No Cache**
at least not inconsistent. With v1.1 of REST API serious trading was impossible, because the balance/orderstatus took several seconds or even minutes to refresh and also placing an order sometimes took that long, while depending on which REST call you did, you got contradary responses.

### nice to have:

**Orderbook depth:**
maybe allow few more depths for orderbook? I would like to use between 50 and 100, but allowed are only [1, 25, 500].

**Cancel Order:**
Add possiblity to cancel all open orders and all orders of a given symbol. (edit: with a single call of course)

**clientOrderId:**
Expand the usage of this CID. Other exchanges allow to use it to cancel/get order.

**Comment by bittrex-pete** [comment]
Hi @Serpens66 thanks for the feedback. I've passed it along to the team. Notes on a few of them below.

**MinTradeSize** changes periodically. It doesn't change constantly. There's no defined schedule for it. The operations team just updates them periodically when they feel it's needed. If it was me, I'd probably just update them all once on start up and then again whenever I get a min trade size error or maybe like once every hour/few hours.

 **Get executions**: The proceeds field is not rounded. The total quote currency paid for a buy order is proceeds + commission. For a sell order the quote currency received is proceeds – commission. Commission is always represented in quote currency.

**No Cache**: We do edge cache responses to requests for public market data over the REST API. This is necessary to keep the system safe from malicious actors. The expirations are short, but it's true that the REST API alone is not sufficient for any serious algorithmic trading. Our stance is that if you need data with sub-second accuracy, you should use the websocket for those needs instead of polling with the REST API.

**Cancel order**: Just released! See https://bittrex.github.io/api/v3#operation--orders-open-delete
