### ISSUE TITLE
get char data with merging results of websocket are not matched

### ISSUE THREAD

**Issue by marslep** [Bittrex/bittrex.github.io#17]
Hello everybody, I’m trying to develop my own get char data with merging results of websocket and rest API It seems that the results I get from websocket and from rest api are not matched.
I called get ticks once. then used summary data to calculate the correct open close high and low.
But my new bars open and close and high and low were not matching bittrex api if I do the rest api call again.
Is there any known problem? what workaround can I do?

**Comment by jayarjo** [comment]
Not sure if it is the reason in your case, but OHLC prices will differ depending on the interval for which they are calculated. If you somehow manage to calculate it with ms precision from exactly the same timestamp they should theoretically match. But no idea how one could possibly accomplish this with all the delays and order mismatch.

**Comment by laserlance** [comment]
I have done extensive testing on my own before implementing the websocket connection. I have not seen a discrepancy; trades that are seen on the REST API are always seen on the websocket, and vice-versa.
If, for example, you are trying to get one-minute OHLCV data, and you are using the REST API, then you need to make the API call shortly after the start of the next minute. If you try to call the API at 55-seconds of the current minute, then you may miss trades that occur within the last 5-seconds of the minute and you will have a discrepancy. Using the websocket means that you can calculate these OHLCV values almost directly after the close of the minute. It is much more efficient/reliable as long as the connection remains connected. If you lose connection to the websocket, you will miss the trades that occur in the time that you are disconnected unless you can get re-connected quickly. 
The network connection also has something to do with this. You should have a very fast connection, preferably close to the Bittrex servers, so that you do not have delays in receiving the data. The data has a timestamp, but that doesn't mean that you will receive the data at the same time of the timestamp; there will always be some delay. My service, ClueDex, uses a 40Gbps connection, for example and I get data a few ms after the timestamp of the data. Some food for thought.

**Comment by jayarjo** [comment]
@laserlance what are you using ClueDex for? Never heard about it.

**Comment by laserlance** [comment]
@jayarjo The main purpose of the ClueDex project is to create cryptocurrency market indexes through the use of Artificial Intelligence. The Indexes offer insight into which markets are trending at any given moment and suggest a level of momentum. They're different from traditional volume indexes in that they don't consider the price of the asset at all. Traditional indexes were made for traditional assets, and cryptocurrencies are anything but traditional. Using social metrics, which I believe are analogous to traditional metrics like company profit performance, the indexes accurately portray if someone is about to gain or lose money. I deliver these signals via both a REST API, through websockets (called TrendSockets™), and a GUI, which helps to fund the Indexes.
