### ISSUE TITLE
MarketName in QueryExchangeState response is always null. 

### ISSUE THREAD

**Issue by arpluta** [Bittrex/bittrex.github.io#18]
Hi, 

I sent subscription message to Bittrex gateway: 
`{"H":"c2","M":"QueryExchangeState","A":["BTC-LTC"],"I":0}`
and MarketName in response is always empty:
`{"M":null,"N":17974,"Z":...`

**Comment by Xavier59** [comment]
Yes I also noticed it ... Definetly a problem coming from bittrex.

**Comment by jayarjo** [comment]
Still have to use beta then?

**Comment by laserlance** [comment]
The folks at Bittrex have been a lot better at communicating with us these days. I think they would tell us when they have rolled out all of the changes to the production websocket so I'm using the beta websocket until they say differently.

**Comment by lnedialkov** [comment]
Hey Bittrex folks, any updates here?

**Comment by pdotmidge** [comment]
Any `beta` resources still responding are just DNS mappings to production that we haven't cleaned up yet. You should switch ASAP to `socket.bittrex.com`, since we'll likely give little notice before that cleanup happens given the beta has been over for so long.

The `MarketName` field was fixed in production in an early September release. I have fallen behind on GH, but have added some folks to the team that will be helping out soon.
