### ISSUE TITLE
API v3 DELETE definition mistake

### ISSUE THREAD

**Issue by surinpeter** [Bittrex/bittrex.github.io#180]
Hi BITTREX, I think, there is a mistake in API v3 DELETE definition.

![v3v](https://user-images.githubusercontent.com/71847235/94370523-d2940880-00f0-11eb-996e-60575a45081a.png)
![v3a](https://user-images.githubusercontent.com/71847235/94370528-d9228000-00f0-11eb-84e8-4a09eb541b94.png)

**Comment by bittrex-pete** [comment]
Hi @surinpeter thanks for reporting this, but it is intentional. The field mappings provided in this guide refer to the v1 and v3 response models, not the request models. In v1 when you cancel an order, the uuid is returned. In v3 when you cancel an order, then entire order model is returned. The equivalent of the uuid in v1 response is the id in the v3 response.

**Comment by surinpeter** [comment]
OK, I understand, Thank You :-) :-)
