### ISSUE TITLE
QueryExchangeState does not send back the entire orderbook

### ISSUE THREAD

**Issue by Xavier59** [Bittrex/bittrex.github.io#19]
`QueryExchangeState` doesn't send back the full order book as per the documentation :
 
> **QueryExchangeState**
> Allows the caller to retrieve the full order book for a specific market.

It only sends back the first `50x10 = 500` orders of each side.
This is misleading.

I admit this to be true, but I would like to be reassured. Does `SubscribeToExchangeDeltas` send the orders which were 500+ once the market move in one direction even if they are not new orders ?

**Comment by laserlance** [comment]
As I understand, `SubscribeToExchangeDeltas` sends only the updates to the order book from the time you call it, forward; it does not look back.

**Comment by mellertson** [comment]
After you send `SubscribeToExchangeDeltas` is sends two messages.  First `snapshotOrderbook` contains the presumably the "entire order book".  I put it in quotes, because I haven't confirmed whether it's truly hte entire order book or just most of it.  

After you recieve the `snapshotOrderbook` messages, you'll recieve `updateOrderbook` messages every time the order book is updated.

**Comment by pdotmidge** [comment]
Correct. QES returns 500 levels on each side. A doc update is pending.
