### ISSUE TITLE
Balances are cached for unknown period - please document this behavior and perhaps better to invalidate cache immediatelly after an order is closed? 

### ISSUE THREAD

**Issue by BadgerTheAdger** [Bittrex/bittrex.github.io#220]
Hey, guys!

I am using balances GET to retrieve balances, and orders POST to post an order, both endpoints of the v3 version. 

When I post an order and it gets closed immediately, I query balances. Then I validate that the amounts returned from API match the order placement response.

However, when I query balances, the API still returns old data. I tried querying balances in like 4-5 seconds after order response, and this did fix the issue i.e the balances returned from the API were of the latest state.

Here's the log of requests/responses:

### REQUEST balances GET
___
### RESPONSE
___
[{"currencySymbol":"BTC","total":"0.00369198","available":"0.00369198","updatedAt":"2021-01-04T06:36:04.67Z"},{"currencySymbol":"BTXCRD","total":"1524.94024306","available":"1524.94024306","updatedAt":"2021-01-04T06:36:18.66Z"},{"currencySymbol":"USDT","total":"5.89272203","available":"5.89272203","updatedAt":"2021-01-04T06:36:04.67Z"}]
___
### REQUEST orders POST
___
{"marketSymbol":"BTC-USDT","direction":"SELL","type":"LIMIT","timeInForce":"GOOD_TIL_CANCELLED","limit":33108.52010003,"quantity":0.00350738}
___
### RESPONSE
{"id":"49820879-0f6f-40fc-982b-8a4cc959ea38","marketSymbol":"BTC-USDT","direction":"SELL","type":"LIMIT","quantity":"0.00350738","limit":"33108.52010003","timeInForce":"GOOD_TIL_CANCELLED","fillQuantity":"0.00350738","commission":"0.23224831","proceeds":"116.12416121","status":"CLOSED","createdAt":"2021-01-04T06:39:28.81Z","updatedAt":"2021-01-04T06:39:28.81Z","closedAt":"2021-01-04T06:39:28.81Z"}
___
### REQUEST balances GET
___
### RESPONSE <--- **Please note here that the balances returned are still of the old state although the order was fully filled!!!**
[{"currencySymbol":"BTC","total":"0.00369198","available":"0.00369198","updatedAt":"2021-01-04T06:36:04.67Z"},{"currencySymbol":"BTXCRD","total":"1524.94024306","available":"1524.94024306","updatedAt":"2021-01-04T06:36:18.66Z"},{"currencySymbol":"USDT","total":"5.89272203","available":"5.89272203","updatedAt":"2021-01-04T06:36:04.67Z"}]
___
### REQUEST balances GET  // in 5 seconds or more
___
### RESPONSE
[{"currencySymbol":"BTC","total":"0.00018460","available":"0.00018460","updatedAt":"2021-01-04T06:39:28.81Z"},{"currencySymbol":"BTXCRD","total":"1525.17133012","available":"1525.17133012","updatedAt":"2021-01-04T06:39:38.73Z"},{"currencySymbol":"USDT","total":"121.78463493","available":"121.78463493","updatedAt":"2021-01-04T06:39:28.81Z"}]
___

**Comment by bittrex-pete** [comment]
Hi @BadgerTheAdger - Are you saying that you're seeing stale balances for 4-5 seconds? If so, that's very unexpected. It is true that balances are cached for a short period of time. The update interval on that cache is currently set to around 50ms. Generally that's fast enough that if somebody places an order, waits for the response, and then queries balances the cache will have already been updated. Of course that depends on network latency and how close your code is running to the server. People who are interested in minimizing that stuff typically use the websocket for updates instead of querying via the API. That's what I'd recommend if you need sub-second latency updates.

**Comment by BadgerTheAdger** [comment]
Hmm, do you think it's better to be constantly updating the cache every n ms or it's better to build some reactive mechanism that will invalidate the cache of balance after balance operations (deposits, withdrawals, orders, etc.)? I think the second option suits you better. Just my 5 cents

**Comment by BadgerTheAdger** [comment]
Ok I have just switched from 4 seconds to 50 ms delay before querying the balances, and I still got this old state issue 
![image](https://user-images.githubusercontent.com/33373431/103615263-f27a6a00-4f32-11eb-892c-8d6f6809a8bb.png)

**Comment by BadgerTheAdger** [comment]
100 ms seems to work

**Comment by BadgerTheAdger** [comment]
UPD: even 100 ms returns old-state data!
I believe this is also based on how many requests a user has done? i.e if too many then the cache is increased or what?

**Comment by bittrex-pete** [comment]
I followed up on this with some folks and it has more to do with overall amount of activity on the system. When there is a lot going on like there has been recently this can take longer. It is also fairly variable depending on what's going on moment to moment on the system. That's why 100ms seemed fine for a while and then later not so much. Obviously the longer you delay the safer it is, but it's asymptotic so there's a risk/benefit decision to be made. If you can wait a second that should be nearly always safe, but it is also nearly always a waste of time. 

All that being said, I'd really recommend using the websocket for these updates instead of querying. You'll get a result faster than you ever could with this approach and you won't have to worry about this timing.

**Comment by BadgerTheAdger** [comment]
Yeah. The reason why I'm using HTTP for this scenario is that it's an integration test :). Of course in a real scenario, it would be a WebSocket, but I just have integration tests testing all HTTP endpoints
