### ISSUE TITLE
Either of the "Limit", "FillQuantity", "Commission" fields returned from orders POST are wrong

### ISSUE THREAD

**Issue by BadgerTheAdger** [Bittrex/bittrex.github.io#221]
Hey guys!

I have the following scenario:

1) Place Limit Order
2) Get info about order result
3) Wait 3-4 seconds, so that API has time to invalidate the balances cache
4) I query balances GET
5) I calculate balances manually (expected) and compare them with those returned from API (actual)

And I get mismatching values.

Please, check the log below:

### REQUEST Balances GET
___
### RESPONSE
[{"currencySymbol":"BTC","total":"0.00018460","available":"0.00018460","updatedAt":"2021-01-04T06:39:28.81Z"},{"currencySymbol":"BTXCRD","total":"1525.17133012","available":"1525.17133012","updatedAt":"2021-01-04T06:39:38.73Z"},{"currencySymbol":"USDT","total":"121.78463493","available":"121.78463493","updatedAt":"2021-01-04T06:39:28.81Z"}]
___
### REQUEST Orders POST
{"marketSymbol":"BTC-USDT","direction":"BUY","type":"LIMIT","timeInForce":"GOOD_TIL_CANCELLED","limit":32984.3434,"quantity":0.00350439}
___
### RESPONSE
{"id":"1cb87b3e-1399-4633-a4ac-bf1f7378aaf2","marketSymbol":"BTC-USDT","direction":"BUY","type":"LIMIT","quantity":"0.00350439","limit":"32984.3434","timeInForce":"GOOD_TIL_CANCELLED","fillQuantity":"0.00350439","commission":"0.23117930","proceeds":"115.58965483","status":"CLOSED","createdAt":"2021-01-04T06:58:04.5Z","updatedAt":"2021-01-04T06:58:04.5Z","closedAt":"2021-01-04T06:58:04.5Z"}
___
### REQUEST Balances GET
___
### RESPONSE
[{"currencySymbol":"BTC","total":"0.00368899","available":"0.00368899","updatedAt":"2021-01-04T06:58:04.5Z"},{"currencySymbol":"BTXCRD","total":"1525.17133012","available":"1525.17133012","updatedAt":"2021-01-04T06:39:38.73Z"},{"currencySymbol":"USDT","total":"5.96380080","available":"5.96380080","updatedAt":"2021-01-04T06:58:04.5Z"}]
___

As you can see, the amount of USDT before the order was 121.78463493. The filled quantity is 0.00350439, limit price = 32984.3434. Commission (in USDT) is 0.23117930.

So, expected new USDT should be 121.78463493 - (0.00350439 * 32984.3434) - 0.23117930 = 5.96345246247. 

But, the actual new USDT that was returned from API was 5.96380080.

5.96345246247 != 5.96380080.

Could you please clarify, is it an issue on API or client side? How do I fix these calculations?

Thanks

**Comment by bittrex-pete** [comment]
Hi @BadgerTheAdger - The quantity and limit price put an upper bound on what you might end up paying for an order, but depending on how you set the limit and what other people on the market are doing, you may end up with better price than the one you asked for. In this case, when you place the order there was already somebody with an open order willing to sell for less than your limit, so you got that price instead of you (higher) limit. 

I can tell this is what happened because the response to your POST /orders request returned already filled. If it had returned as status open with fillQuantity 0 and then been filled by someone else's order at a future point in time, your calculation would have been closer to accurate.  It's also possible for an order you place to be partially filled initially (fillQuantity > 0 but < quantity) in which case you'll get better than the limit price on part of your order and the limit price on the rest at some future point in time.  The easiest way to see the details of what happened after the fact is to check out https://bittrex.github.io/api/v3#operation--orders--orderId--executions-get for the order in question. It will tell you exactly what price you got on different portions of the order.

One other thing to note is that multiplication and division results are truncated to 8 decimal points in our platform. So your balance calculation should look more like this: 121.78463493 - TRUNC(0.00350439 * 32984.3434, 8) - 0.23117930 = 5.96345247

**Comment by BadgerTheAdger** [comment]
Thanks, I will just leave the info here for other people's references (copied from https://github.com/Bittrex/bittrex.github.io/issues/219)

Proceeds: amount in the quote
fillQuantity: amount in the base
The average price of an order is calculated this way: Proceeds / fillQuantity

(Soon to be in the doc)
