### ISSUE TITLE
SignalR connect to order issue 

### ISSUE THREAD

**Issue by BadgerTheAdger** [Bittrex/bittrex.github.io#225]
Hi everyone, 
I have an issue with connecting to the order WS channel.

First, I send the Authenticate message etc. and I get successfully authenticated.
Then, I Invoke "Subscribe" function, passing a param [ [ "order" ] ]. (I Invoke this on the same hubProxy I invoked Authenticate on). 

Then I get the following exception:
> There was an error invoking Hub method 'c3.Order'

I have no idea what exact error it was... It just says error...

Do you have any idea what that could be based on the steps I make this subscription I described above?

**Comment by bittrex-pete** [comment]
Hi @BadgerTheAdger - high level that sounds right. I would guess that the issue has something to do with arrays and the param. Depending on what what signarlR package and what programming language you're using on the client there can be small differences in exactly what needs to be sent in as the param to get the client to send the right thing to the server. There are some basic examples in various languages here: https://bittrex.github.io/api/v3#topic-Example-Socket-Clients   They all subscribe to the balance channel instead of the order channel, but the process of subscribing is exactly the same between those two.  

If memory serves, I think you were using C#. In which case the code for subscribing should look something like this. string[] channels is just an array of channel names. You can find the full example at the link above.

```
        public async Task<List<SocketResponse>> Subscribe(string[] channels)
        {
            return await _hubProxy.Invoke<List<SocketResponse>>("Subscribe", (object)channels);
        }
```

**Comment by BadgerTheAdger** [comment]
Hi @bittrex-pete 

Thanks, that helped! I did not cast channels to object so that was the issue and so it . Also, I needed to add a listener to the order method.

By the way, could you please clarify the following: in the WS response there's an object called "Delta". This has the same schema as HTTP order info, and also I have run some tests that placed 10 orders in a loop and awaited for the WS response, and the WS response was always the same as HTTP one. However, "Delta" usually has a meaning of "a change", "a part", etc.

So will this WS endpoint always send me the full order info as it's been doing in my case today or it can at some point send "delta" i.e partial info of an order or change info of an order. In the second case, I will need to poll HTTP API after a WS message is received to get full order info.

**Comment by bittrex-pete** [comment]
Hi @BadgerTheAdger - The socket will always send the full object. I'm not a fan of our usage of the word "delta" in this case either. I guess the philosophy is that it's a delta from the snapshot in that it's one order that's changing out of all your orders, but it does make people wonder for the reason that you stated.  The object in the deltas will always be full replacements within some scope. For orders it's a whole order. For balances it's a balance of one currency. For orderbook it's one level on the bid or ask side of the book for a given market. Etc. The unique key documented in the stream's documentation should give you a good idea as to the scope of the update.  This is discussed a bit more in https://bittrex.github.io/api/v3#topic-Synchronizing especially step 6.

**Comment by BadgerTheAdger** [comment]
Makes sense thanks
