### ISSUE TITLE
INVALID_CONTENT_HASH as a response for every request

### ISSUE THREAD

**Issue by 1337sc** [Bittrex/bittrex.github.io#242]
Hello! When I try to receive executions for a market symbol BTC-USDT, place an order or get balances the response is always INVALID_CONTENT_HASH. The api-key, api-content-hash, api-signature and content-type fields are set. What may cause such a problem and how to solve it?
There is an example of the request attached below (private information is hidden).

![Безымянный](https://user-images.githubusercontent.com/46076326/108621429-366df380-743b-11eb-9dc1-96fb4e89efa1.png)

**Comment by bittrex-pete** [comment]
Hi @1337sc That error means that the content hash you're sending doesn't match up with the one the system is computing for the request it received. The content hash is computed based on the request body. Since GETs don't have request bodies, the empty string should be  used as the input instead (so content hash is the same for all GETs). You must be doing something different in your computation.  It should be `cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e`.

**Comment by 1337sc** [comment]
Thank you, it was really my fault since I created the hash in a wrong format, so the hash you provided helped a lot.
