### ISSUE TITLE
Deposit History Pagination Issue 

### ISSUE THREAD

**Issue by mchalise** [Bittrex/bittrex.github.io#246]
I am trying to pull all my Deposit History. which is around 250 deposit records.

1. HIT GET /deposits/closed with pageSize: 200 , which returns 200 records.
2. I plucked last transaction ID from above repose and pass it in next response with pageSize: 200, nextPageToken: ID, which is giving me {:code=>"INVALID_SIGNATURE"}
3. similarly I tried passing that same ID to previousPageToken and it's returning old records. not the other remaining ones.
4. I also tried with First Transaction ID but no luck.

Is there a bug in the pagination code or am I missing some query params? Can someone help me with this. 
Thanks in advance.

**Comment by bittrex-pete** [comment]
Hi @mchalise INVALID_SIGNATURE means something is wrong with the value you're putting in the Api-Signature header. Since it's working for the initial request and failing for the second page, I'm guessing that maybe your signing code isn't taking into account the query parameters in the URL when computing the signature.

**Comment by mchalise** [comment]
I found a way around @bittrex-pete . The issue is when I pass both pageSize and nextPageToken as query params, its giving me that error. But I got the pagination part workaround without pageSize. Closing this ticket.
