### ISSUE TITLE
Failing to log in.

### ISSUE THREAD

**Issue by PopeNobody** [Bittrex/bittrex.github.io#251]
I have been trying to adapt to v3, and it is defeating me.

Is there a brief code example which shows how to send an authenticated request to the v3 server?

I have seen many cries for help on this, but I have not found any solutions.

**Comment by RT-Tap** [comment]
Are you trying to login via REST or websockets?  They are 2 different protocols.  I just started writing some code in python for a project,  I can share it with you if your using python.  It's heavily commented as I went through it commenting every line when I started so you should be able to understand what's going on and reference it to the API documentation and go from there. The REST request code is built from scratch and I slightly modified the reference code for websockets.  BTW you can find reference code for websockets here: https://bittrex.github.io/api/v3#introduction

**Comment by PopeNobody** [comment]
I actually just got past it.  I am writing in javascript.

I am using the restful api, I envy those who are using websockets. It seems to have a lot more documentation.  Which is not to say it has a lot of documentation.

**Comment by RT-Tap** [comment]
Well, they take care of two different things.  REST gives you past data and websockets sends you info as it happens, it's up to you whether you want to log it or process it or what have you so it really depends on what your trying to do.  And yes I wouldn't say the documentation is the gold standard of documentations but it gets the job done.

**Comment by bittrex-pete** [comment]
@RT-Tap that's basically it. High level: REST is used in the v3 API for pulling information and for performing operations. Websockets in the v3 API are used for getting updates pushed to you as things happen. There's a division of available operations based on that which is why you don't see things like request for historical candles on the socket side. Theoretically we could have built the system such that everything is done via the socket, but sockets are trickier to use and not everyone wants to deal with them so it makes sense to have a REST option. Conceptually what we went for with this API is that REST is good enough for basic use cases so you can get started and then you can layer the socket on top of that for more sophisticated use cases where you need fast live updates.

**Comment by bittrex-pete** [comment]
@PopeNobody Sounds like you figured it out, but if you have questions/need help still let me know
