### ISSUE TITLE
INVALID_SIGNATURE when params are included in Axios call

### ISSUE THREAD

**Issue by chrisjaimes** [Bittrex/bittrex.github.io#257]
Hi there,

I am trying to make an api call to Bittrex v3 using nodejs and axios.

The following code works:

```
const response = await axios.get("https://api.bittrex.com/v3/orders/closed", {
    headers: { ...headersObj },
  });
```

However, as soon as I add parameters to the call, I get an `INVALID_SIGNATURE` response.
Example:
```
const response = await axios.get("https://api.bittrex.com/v3/orders/closed", {
    headers: { ...headersObj },
    params: {
      pageSize: 20
    }
  });
```

Why is this happening? Am I missing something? Let me know if you need more code to reproduce, but I think what I have provided is enough to understand the issue I'm facing. Thank you!

**Comment by bittrex-pete** [comment]
INVALID_SIGNATURE means that the system does like the value your provided for the Api-Signature header. Given that it's working fine for you without the query params and then breaks when they are added, I would guess that the issue is that the query params aren't being included in the string that you're using to generate the signature.  It should look like this (just with a current timestamp):

`1619397382161https://api.bittrex.com/v3/orders/closed?pageSize=20GETcf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e`

**Comment by chrisjaimes** [comment]
You are absolutely right. Adding the query params to the URI before generating the signature solved it 👍
