### ISSUE TITLE
Historical endpoint not working for current year

### ISSUE THREAD

**Issue by marianogoldman** [Bittrex/bittrex.github.io#289]
Hi, I'm getting an error trying to retrieve historical data when using current year. Previous years work fine:

`GET https://api.bittrex.com/v3/markets/ETH-BTC/candles/TRADE/DAY_1/historical/2020` is ok.
`GET https://api.bittrex.com/v3/markets/ETH-BTC/candles/TRADE/DAY_1/historical/2021` returns error:

```
HTTP/1.1 400 Bad Request
...
{
  "code": "STARTDATE_OUT_OF_RANGE"
}
```

I managed to get current year  using another endpoint:
`GET https://api.bittrex.com/v3/markets/ETH-BTC/candles/TRADE/DAY_1/recent`, but it also retrieves part of the previous year overlapping results with the 2020 call.

Wouldn't it be possible to make 
`GET https://api.bittrex.com/v3/markets/ETH-BTC/candles/TRADE/DAY_1/historical/2021` to get from 2021-01-01 up to today?

Thanks.

**Comment by bittrex-pete** [comment]
Hi @marianogoldman - recent and historical are split up to make it easier for us to manage how they're edge cached. We could have made it so that recent always returned 2021-01-01 to current for example, but we didn't because in many cases people want more data than that (e.g. if it's currently 2021-01-02 and you're making the request it would be lame to just get back one day worth of data). I guess we could have built another version of recent or provided a parameter on recent to give it the behavior you're looking for so you could avoid deduplicating between recent and historical, but we didn't think the duplicate data would cause that much grief so it's not something we've ever prioritized.
