### ISSUE TITLE
missing messages and non-sequential fill id's

### ISSUE THREAD

**Issue by nahatx** [Bittrex/bittrex.github.io#32]
When I subscribe to ALL markets on https://socket.bittrex.com/signalr using SubscribeToExchangeDeltas and QueryExchangeState, I will after a seemingly random period of time stop receiving updates for some markets, and I will also begin receiving late fills, sometimes 10+ minutes late. Currently, I simply reconnect when one of these things occurs, but this is not the desired behavior.

Is this expected behavior i should handle or should I reexamine my own code to resolve? I'm wondering if you expect people to subscribe to data for all markets? Is there anything I should know to help me successfully subscribe to all markets?

Also, fill ID's are non sequential, they skip numbers and I don't understand why this is the case? 
I expect 123, 124, 125 so you know if there are missing trades in your history, however what fill ID's actually produce resembles 123, 128, 133, etc.. skipping multiple numbers between each fill. Is there a reason fill ID's are non sequential?

I also think it would be a good idea to include a timestamp in each update to help maintain continuity.

Thanks for your time, I've tried getting with support, but they seemed to respond as if they didn't even read my question, twice.

**Comment by laserlance** [comment]
The speed at which you receive messages is partially related to the speed of your connection to the Bittrex servers. You can measure this through a couple of ways. One is to ping the Bittrex servers, the other is to look at the fill timestamp and compare that with your local timestamp, assuming your local clock is synchronized. Checking the speed of your connection can give you an idea if this is the problem, or not. If speed is not the issue then perhaps there is some memory issue on your system/in your code?

The fill IDs have never been sequential. I postulate that the reason for the non-sequential nature of this is because some orders are canceled before they are filled. It may be possible that each order gets a fill ID before it is filled. When the order is cancelled, there is a void left in the ordering of this. This is just speculation, however.

As for the timestamp idea, I personally use the timestamp of when the order is filled as a timestamp.

**Comment by nahatx** [comment]
Thanks for the response. 

I also use the Fill timestamp. Its just strange, no out of order nonces, and no other fills coming in late while subscribing to all markets at once. Just occasional random fills that are 10-600+ seconds late. I'll also over time begin receiving less messages per second, presumably due to missing/late updates. I guess I handle this as best as possible, as long as it's documented. I'll poke my code a bit more as well.

And thank you for confirming I'm not crazy regarding the Fill ID's.

**Comment by laserlance** [comment]
You may be onto something here. While I do not record the timestamp on when I receive the data, the way my system is setup is that I am able to tell if there is an anomaly in the data. For the trades you mention, there is definitely an anomaly. 

The two trades with the same timestamp apparently arrived at my servers at the same time. However, the odd timestamp trade did not arrive in the same packet of information, apparently. It arrived in a timely manner, but only because of a redundant system that ensures I get all of the trades in a decent time frame. 

Do you have the trades with FillIDs 180901669 and 180900232 for the same market? These are two trades which appear to be anomalies on my end. Their timestamps are 2018-10-05 21:24:31.317 UTC and 2018-10-05 21:12:11.883 UTC, respectively, which are after and before the trades in question.

So, it appears that perhaps there is really some issue with not receiving all of the trades via the websocket. 

Also, I'm using the beta endpoint, and I'm also subscribing to all markets, if any of that matters.

**Comment by nahatx** [comment]
I do not have those two trades, however if they were included in later messages, I may not have been running at that time. I have also verified that the REST API returns the same information, implying this issue is not isolated to websocket data. I believe I have confirmed this issue is present using https://www.bittrex.com/signalR/, https://socket.bittrex.com/signalr, and https://beta.bittrex.com/signalr endpoints, however I am double checking now just in case. Still no working wss endpoint. 

As for the 7-8 second discrepancy, the 'arrival time' was actually before the timestamp, and I assumed it was an incongruity between my server time and Bittrex.com server time. Didn't bother me too much, however I have corrected this.

Thanks again for the response.

**Comment by jayarjo** [comment]
@laserlance still sitting on beta?

**Comment by laserlance** [comment]
@jayarjo Yes, but I am using redundant systems on different endpoints. I put them together and can see from which system/endpoint the trades were seen on.

**Comment by nahatx** [comment]
I can confirm different endpoints behave in the same way as far as receiving late messages, however I was not running them concurrently. 
Can you confirm the data on each endpoint has been identical?

**Comment by laserlance** [comment]
@nahatx That's sort of what I'm saying; I'm getting data from all of the endpoints that I know about and there appears to be some discrepancy, but I'm not absolutely sure because it could be that data arrives at one system before it arrives at another and that's perhaps why I'm seeing different data on different endpoints. In other words, if there's a collision, I don't log it so I don't know; I can just see that data are coming from the different endpoints where I would expect them to arrive at a single endpoint consistently.

**Comment by laserlance** [comment]
I believe I've found an underlying issue as to why there are non-sequential Fill IDs on the websocket, thanks to an astute customer of mine. While QueryExchangeState returns a field "FillType", and indicates whether or not a fill is partial or full, the SubscribeToExchangeDeltas does not return partial fills at all, apparently. SubscribeToExchangeDeltas is actually missing the "FillType" field altogether, which may be another issue to raise as SubscribeToExchangeDeltas has been described as what we're supposed to use if we want continuous updates, as opposed to polling QueryExchangeState, which I think should imply that the fields sent with SubscribeToExchangeDeltas would be identical to QueryExchangeState fields. Since a partial fill has a FillId, then this could explain one reason why Fill IDs are not sequential--although Fill IDs are also not sequential on the REST API, which does show partial fills.

**Comment by enggtikkle** [comment]
> When I subscribe to ALL markets on https://socket.bittrex.com/signalr using SubscribeToExchangeDeltas and QueryExchangeState, I will after a seemingly random period of time stop receiving updates for some markets, and I will also begin receiving late fills, sometimes 10+ minutes late. Currently, I simply reconnect when one of these things occurs, but this is not the desired behavior.
> 
> Is this expected behavior i should handle or should I reexamine my own code to resolve? I'm wondering if you expect people to subscribe to data for all markets? Is there anything I should know to help me successfully subscribe to all markets?
> 
> Also, fill ID's are non sequential, they skip numbers and I don't understand why this is the case?
> I expect 123, 124, 125 so you know if there are missing trades in your history, however what fill ID's actually produce resembles 123, 128, 133, etc.. skipping multiple numbers between each fill. Is there a reason fill ID's are non sequential?
> 
> I also think it would be a good idea to include a timestamp in each update to help maintain continuity.
> 
> Thanks for your time, I've tried getting with support, but they seemed to respond as if they didn't even read my question, twice.

I have been facing the same issue where i have subscribed to all markets using single websocket connection and have been seeing missed trades and delayed updates upto few minutes. Did you find any solution for this? Were you able to solve this issue with opening websocket connection for each market?

**Comment by cyrus19909** [comment]
This issue has been fixed.
