### ISSUE TITLE
How to unsubscribe from updates from a particular symbol?

### ISSUE THREAD

**Issue by serggulko** [Bittrex/bittrex.github.io#35]
Let's say, I subscribed on five different instruments. After a certain time I want to adjust my subscription by stopping getting updates on instruments #1 and #4. 

Is there a way I can do it?

**Comment by slidenerd** [comment]
You will have to build a subscription class around it to manage it, call a subscribe method, add the pair to the list of active subscriptions, when you reconnect due to a connection failure or something, just unsubscribe to everything meaning clearing the dictionary and sending the subscribe message again

**Comment by pdotmidge** [comment]
There is currently no unsubscribe method. You'll need to do as @slidenerd suggests or just ignore the data when you no longer care about it.
