### ISSUE TITLE
Api-Content-Hash

### ISSUE THREAD

**Issue by duynguyen-lunex** [Bittrex/bittrex.github.io#90]
Hi,

What should we populate this header with in the new api? Documentation says:
var contentHash = CryptoJS.SHA512(content).toString(CryptoJS.enc.Hex);

but this just gives back INVALID_CONTENT_HASH.

What should content be for below request
https://api.bittrex.com/v3/withdrawals/closed?pageSize=20
In my example content = "pageSize=20" so I got INVALID_CONTENT_HASH error
var contentHash = CryptoJS.SHA512("pageSize=20").toString(CryptoJS.enc.Hex);
Please give me an advice
Thanks

**Comment by cyrus19909** [comment]
Hi,

From the looks of it , i see where the issue is. 
In the code snippet `var contentHash = CryptoJS.SHA512("pageSize=20").toString(CryptoJS.enc.Hex);` , the content refers to the body which will be an empty string in this case . The `?pageSize=20` will just be a query parameter like you have in https://api.bittrex.com/v3/withdrawals/closed?pageSize=20 . Please let me know if this helps resolve your issue.

Thanks

**Comment by duynguyen-lunex** [comment]
tks so much
